apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world
data:
  nginx: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location ~ \.php$ {
            root           html;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  /app$fastcgi_script_name;
            include        fastcgi_params;
        }
    }